// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCreWWjVAZIks7BXVtTx2YKjmtwi29IL88',
    appId: '1:34859493529:web:0600c959cabe4f4a5ff008',
    messagingSenderId: '34859493529',
    projectId: 'fir-auth-126a6',
    authDomain: 'fir-auth-126a6.firebaseapp.com',
    storageBucket: 'fir-auth-126a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATDzz3IjpQkfbL7Nq3gGkp1fd5wok13W0',
    appId: '1:34859493529:android:ff43aa83f81fb6625ff008',
    messagingSenderId: '34859493529',
    projectId: 'fir-auth-126a6',
    storageBucket: 'fir-auth-126a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy7XGHZx6o5PD7IKQqCj-UDwUJ9vqe4HU',
    appId: '1:34859493529:ios:52d86f3928b5ff005ff008',
    messagingSenderId: '34859493529',
    projectId: 'fir-auth-126a6',
    storageBucket: 'fir-auth-126a6.appspot.com',
    iosBundleId: 'com.example.firebaseaut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy7XGHZx6o5PD7IKQqCj-UDwUJ9vqe4HU',
    appId: '1:34859493529:ios:8b2eee4a23c47ae55ff008',
    messagingSenderId: '34859493529',
    projectId: 'fir-auth-126a6',
    storageBucket: 'fir-auth-126a6.appspot.com',
    iosBundleId: 'com.example.firebaseaut.RunnerTests',
  );
}
